// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImc9o4SZWLGIhV_SxOgNIDO3jzpk3xRU',
    appId: '1:191666435178:web:05aaedb63fc15268168613',
    messagingSenderId: '191666435178',
    projectId: 'buon-demo',
    authDomain: 'buon-demo.firebaseapp.com',
    storageBucket: 'buon-demo.appspot.com',
    measurementId: 'G-V91XGC4W8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWa8a1yNKMRpBnN0xoOK8XGrOqrg0ejY',
    appId: '1:191666435178:android:a1608c939ea15ecc168613',
    messagingSenderId: '191666435178',
    projectId: 'buon-demo',
    storageBucket: 'buon-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9NbQ3WNpiVD7pEar5vPFRKCU-vv67OQ',
    appId: '1:191666435178:ios:931881cf3ece123e168613',
    messagingSenderId: '191666435178',
    projectId: 'buon-demo',
    storageBucket: 'buon-demo.appspot.com',
    iosClientId: '191666435178-1eb1pbfqchsj1iemsprr9u6ki0re32md.apps.googleusercontent.com',
    iosBundleId: 'apisod.com.buonEcommerce',
  );
}
