// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iMP-lkRST9916WA8U9nt0gA3gAI8faA',
    appId: '1:198239262750:web:fe691764d17254b722760f',
    messagingSenderId: '198239262750',
    projectId: 'buon-online-store',
    authDomain: 'buon-online-store.firebaseapp.com',
    storageBucket: 'buon-online-store.appspot.com',
    measurementId: 'G-S4LVGL1V2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDnRH3lsgxfT2UL4tZiui8zb1HpPYgQ4',
    appId: '1:198239262750:android:ecacb31dbfc637ee22760f',
    messagingSenderId: '198239262750',
    projectId: 'buon-online-store',
    storageBucket: 'buon-online-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdEZWvf4aVWqrkzEd4gegaDZz93eOBzA',
    appId: '1:198239262750:ios:a9ee6f2373d54aa022760f',
    messagingSenderId: '198239262750',
    projectId: 'buon-online-store',
    storageBucket: 'buon-online-store.appspot.com',
    iosBundleId: 'apisod.com.buonOnlineStore',
  );
}
