// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_piN5OCCXG8eeprgamg6fGjx2h6E1RI',
    appId: '1:915357553769:web:ea90b13b009278159b3ef8',
    messagingSenderId: '915357553769',
    projectId: 'buon-prod',
    authDomain: 'buon-prod.firebaseapp.com',
    storageBucket: 'buon-prod.appspot.com',
    measurementId: 'G-127PZWEVLC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyl9pwvqlMr7WPSvh3ROKiEjRA19j9rxk',
    appId: '1:915357553769:ios:c1937810adba1f419b3ef8',
    messagingSenderId: '915357553769',
    projectId: 'buon-prod',
    storageBucket: 'buon-prod.appspot.com',
    iosBundleId: 'awes0m.github.io.buonOnlineStore',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDxYrjg4Xw6PkrjYpiCRaPz5KGtAKU8w',
    appId: '1:915357553769:android:2604d855caf93df19b3ef8',
    messagingSenderId: '915357553769',
    projectId: 'buon-prod',
    storageBucket: 'buon-prod.appspot.com',
  );

}